### ISSUE TITLE
No image after reboot

### ISSUE THREAD

**Issue by rgavril** [mortaca/RGB-Pi#49]
I'm running RBGPI os version 2019.08.06 on a Pi 3b.  

Everything worked fine for a long time but when trying to start my system today something weird happened:

 - There is not image displayed on my PVM, like no video signal is sent to it
 - The startup sound is intermittent: I can hear it for half a second then it pauses after that is starts again and repeats until I cannot hear anything (the boot process probably finishes).
 - I can still login fine trough ssh and I see everything works fine in the console
 - I noticed that there is no python process running making me think that the UI failed to start. Can't hear menu music either, that's why I checked.

I don't know if it helps but I've tried to run rgbpiui.pyc manually trough ssh but I get this error message:

`pi@rgbpi:~/RGB-Pi $ python ./rgbpiui.pyc`
`ALSA lib confmisc.c:767:(parse_card) cannot find card 'ALSA'`
`ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such device`
`ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings`
`ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such device`
`ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name`
`ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such device`
`ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such device`
`ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM sysdefault:ALSA`
`Traceback (most recent call last):`
` File "./rgbpiui.py", line 505, in <module>`
`  File "./rgbpiui.py", line 63, in __init__`
`pygame.error: video system not initialized`

**Comment by rgavril** [comment]
Found the issue, my sd card went banannas:

```
root@rgbpi:/home/pi/RGB-Pi# cat /boot/config.txt
cat: /boot/config.txt: Input/output error
```

```
[  210.093450] FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 22638)
[  210.093463] FAT-fs (mmcblk0p1): Filesystem has been set read-only
[  210.093487] FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 22638)
[  210.093500] FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 22638)
[  210.094765] FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 22638)
[  210.094790] FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 22638)
[  214.511214] FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 22638)
[  214.511234] FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 22638)
[  263.357005] FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 22638)
[  263.357026] FAT-fs (mmcblk0p1): error, fat_get_cluster: invalid cluster chain (i_pos 22638)
```
